#!/usr/bin/env python3
# ================================================================
#  bin2weights.py
#
#  Lab 5 – DNN on MNIST (Custom Network – Group 4)
#  Course: Advanced Embedded Systems (AES)
#  Board: Zybo Z7 – Zynq-7000 (ARM Cortex-A9)
#
#  Description:
#  ---------------------------------------------------------------
#  This script converts binary weight and bias files (little-endian,
#  signed 16-bit integers in Q8.8 fixed-point format) into C header
#  macros suitable for direct inclusion in the embedded DNN
#  inference code running on the ARM Processing System.
#
#  Two representations are generated:
#    • Baseline Q8.8  (int16_t)
#    • Tip 2 Q1.7     (int8_t-like, derived via right shift + saturation)
#
#  The output file (weights_group4.h) contains #define macros
#  with comma-separated values, optimized for static initialization.
#
#  Author: Lello Molinario
#  Academic Year: 2025–2026
# ================================================================

import struct


# ----------------------------------------------------------------
# Function: bin_to_define
# ----------------------------------------------------------------
# Reads a binary file containing int16 values (Q8.8) and converts
# them into a C preprocessor macro of the form:
#
#   #define <name> v0, v1, v2, ...
#
# Parameters:
#   - binfile : path to the input .bin file
#   - name    : macro name to be generated
#   - outfile : open file object where the macro is written
#   - comment : optional descriptive comment
# ----------------------------------------------------------------
def bin_to_define(binfile, name, outfile, comment=None):
    # Read raw binary data
    with open(binfile, "rb") as f:
        data = f.read()

    # Unpack little-endian signed 16-bit integers
    values = struct.unpack("<" + "h" * (len(data) // 2), data)

    # Optional comment for readability/debugging
    if comment:
        outfile.write(f"// {comment}\n")

    # Emit C macro
    outfile.write(f"#define {name} ")

    for i, v in enumerate(values):
        outfile.write(str(v))
        if i != len(values) - 1:
            outfile.write(",")

    outfile.write("\n\n")


# ----------------------------------------------------------------
# Function: bin_to_define_q17
# ----------------------------------------------------------------
# Converts Q8.8 int16 values into Q1.7 representation (Tip 2).
#
# Conversion strategy:
#   - Arithmetic right shift by 1 bit:
#         Q8.8 → Q1.7
#   - Saturation to signed 8-bit range [-128, 127]
#
# This format is useful for memory footprint reduction and
# experimentation with reduced precision inference.
#
# The generated macro name is <name>_q17.
# ----------------------------------------------------------------
def bin_to_define_q17(binfile, name, outfile, comment=None):
    with open(binfile, "rb") as f:
        data = f.read()

    # Original values in Q8.8 format
    values_q88 = struct.unpack("<" + "h" * (len(data) // 2), data)

    values_q17 = []
    for v in values_q88:
        # Q8.8 → Q1.7 conversion (divide by 2)
        x = v >> 1

        # Saturation to int8 range
        x = max(-128, min(127, x))
        values_q17.append(x)

    if comment:
        outfile.write(f"// {comment} (Q1.7 Tip 2)\n")

    outfile.write(f"#define {name}_q17 ")

    for i, v in enumerate(values_q17):
        outfile.write(str(v))
        if i != len(values_q17) - 1:
            outfile.write(",")

    outfile.write("\n\n")


# ================================================================
# Header file generation
# ================================================================
with open("../weights_group4.h", "w") as out:

    # ------------------------------------------------------------
    # File header
    # ------------------------------------------------------------
    out.write("/*\n")
    out.write(" * weights_group4.h\n")
    out.write(" *\n")
    out.write(" * Automatically generated by bin2weights.py\n")
    out.write(" * DNN weights and biases for Lab 5 – Group 4\n")
    out.write(" * Formats: Q8.8 (baseline) and Q1.7 (Tip 2)\n")
    out.write(" *\n")
    out.write(" * Author: Lello Molinario\n")
    out.write(" */\n\n")

    # Header guard
    out.write("#ifndef SRC_WEIGHTS_GROUP4_H_\n")
    out.write("#define SRC_WEIGHTS_GROUP4_H_\n\n")

    out.write("#include <stdint.h>\n\n")

    # ======================= FC0 ================================
    bin_to_define(
        "../group_4/weights/Gemm0_biases.bin",
        "bias0",
        out,
        "FC0 bias: 64"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm0_biases.bin",
        "bias0",
        out,
        "FC0 bias: 64"
    )

    bin_to_define(
        "../group_4/weights/Gemm0_weights.bin",
        "weights0",
        out,
        "FC0 weights: 784 x 64"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm0_weights.bin",
        "weights0",
        out,
        "FC0 weights: 784 x 64"
    )

    # ======================= FC1 ================================
    bin_to_define(
        "../group_4/weights/Gemm1_biases.bin",
        "bias1",
        out,
        "FC1 bias: 32"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm1_biases.bin",
        "bias1",
        out,
        "FC1 bias: 32"
    )

    bin_to_define(
        "../group_4/weights/Gemm1_weights.bin",
        "weights1",
        out,
        "FC1 weights: 64 x 32"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm1_weights.bin",
        "weights1",
        out,
        "FC1 weights: 64 x 32"
    )

    # ======================= FC2 ================================
    bin_to_define(
        "../group_4/weights/Gemm2_biases.bin",
        "bias2",
        out,
        "FC2 bias: 16"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm2_biases.bin",
        "bias2",
        out,
        "FC2 bias: 16"
    )

    bin_to_define(
        "../group_4/weights/Gemm2_weights.bin",
        "weights2",
        out,
        "FC2 weights: 32 x 16"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm2_weights.bin",
        "weights2",
        out,
        "FC2 weights: 32 x 16"
    )

    # ======================= FC3 ================================
    bin_to_define(
        "../group_4/weights/Gemm3_biases.bin",
        "bias3",
        out,
        "FC3 bias: 10"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm3_biases.bin",
        "bias3",
        out,
        "FC3 bias: 10"
    )

    bin_to_define(
        "../group_4/weights/Gemm3_weights.bin",
        "weights3",
        out,
        "FC3 weights: 16 x 10"
    )
    bin_to_define_q17(
        "../group_4/weights/Gemm3_weights.bin",
        "weights3",
        out,
        "FC3 weights: 16 x 10"
    )

    # End of header guard
    out.write("#endif /* SRC_WEIGHTS_GROUP4_H_ */\n")
